[project]
name = "bioagent-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "smolagents[docker,openai,telemetry,toolkit]>=1.21.2",
    "docker>=7.1.0",
]
