name: bioinformatics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - pip
  - r-base
  - r-essentials
  - pip:
      - "smolagents @ git+https://github.com/dionizijefa/smolagents.git"
      - docker>=7.1.0
      - openai>=1.109.0
      - websocket>=0.2.1
      - websocket-client>=1.8.0



