name: bioinformatics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - pip
  - r-base
  - r-essentials
  - pip:
      - docker>=7.1.0
      - openai>=1.109.0
      - websocket>=0.2.1
      - websocket-client>=1.8.0
      - grpcio>=1.74.0
      - opentelemetry-proto>=1.36.0
      - googleapis-common-protos>=1.70.0
      - toml>=0.10.2



